server:
  port: 8072

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: prisoners
          uri: http://prisoners:8080
          predicates:
            - Path=/prisoners/**
          filters:
            - RewritePath=/prisoners/(?<path>.*), /$\{path}
            - RemoveRequestHeader=Cookie,Set-Cookie

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
  file:
    name: logs/app.log