server:
  port: 8072

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: prisoners
          uri: http://prisoners:8080
          predicates:
            - Path=/prisoners/**
          filters:
            - RewritePath=/prisoners/(?<path>.*), /$\{path}
            - RemoveRequestHeader=Cookie,Set-Cookie
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db_url}
    username: postgres
    password: "67626762"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        ddl-auto: validate
        temp:
          use_jdbc_metadata_defaults: false

management:
  endpoint:
    end:
      exposure:
        include: "*"

jwt:
  secret-key: 2e292e323124377c78255f363165246b6c7d684a7379445f5c3b713962